interface ColorProps {
  BACKGROUND: string;
  HIGHLIGHT_COLOR: string;
  NOTIFICATION: string;
  WHITE: string;
  THEME_BLUE: string;
  THEME_DARK_BLUE: string;
  SECONDARY_HIGHLIGHT_COLOR: string;
  THEME_BLACK: string;
}

export const COLORS: ColorProps = {
  THEME_BLACK: '#000000',
  BACKGROUND: '#0B0F15',
  HIGHLIGHT_COLOR: '#4C6793',
  SECONDARY_HIGHLIGHT_COLOR: '#1B2532',
  NOTIFICATION: '#031241',
  WHITE: '#FFFFFF',
  THEME_BLUE: '#0957E0',
  THEME_DARK_BLUE: '#062A98',
};
